-- // DDL_Add_Stock_Flow_Detail
-- Migration SQL that makes the change goes here.

CREATE TABLE STOCK_FLOW_DETAIL(
  ID INTEGER AUTO_INCREMENT,
  QUANTITY INTEGER NOT NULL,
  PRICE_PER_UNIT DOUBLE NOT NULL,
  STOCK_FLOW_ID INTEGER NOT NULL,
  PRIMARY KEY PK_STOCK_FLOW_DETAIL(ID),
  FOREIGN KEY FK_STOCK_FLOW_DETAIL_STOCK_FLOW(STOCK_FLOW_ID) REFERENCES stock_flow(ID)
);

-- //@UNDO
-- SQL to undo the change goes here.

DROP TABLE STOCK_FLOW_DETAIL;
