-- // DDL_Add_Product
-- Migration SQL that makes the change goes here.

CREATE TABLE PRODUCT(
  ID INTEGER AUTO_INCREMENT,
  NAME VARCHAR(30) NOT NULL,
  PRODUCT_TYPE VARCHAR(15) NOT NULL,
  PRICE DOUBLE NOT NULL,
  AVAILABLE BIT(1) NOT NULL,
  PRIMARY KEY (ID)
);

-- //@UNDO
-- SQL to undo the change goes here.

DROP TABLE STOCKPRODUCT;