-- // DDL_Add_Product_Receipt
-- Migration SQL that makes the change goes here.

CREATE TABLE PRODUCT_STOCK_PRODUCT(
  STOCK_PRODUCT_ID INTEGER NOT NULL,
  PRODUCT_ID INTEGER NOT NULL,
  QUANTITY INTEGER NOT NULL DEFAULT 1,
  CLEARANCE VARCHAR(15) NOT NULL,
  PRIMARY KEY (STOCK_PRODUCT_ID, PRODUCT_ID),
  FOREIGN KEY FK_RECEIPT_STOCK_PRODUCT(STOCK_PRODUCT_ID) REFERENCES STOCKPRODUCT(ID),
  FOREIGN KEY FK_RECEIPT_PRODUCT(PRODUCT_ID) REFERENCES PRODUCT(ID)
);

-- //@UNDO
-- SQL to undo the change goes here.

DROP TABLE PRODUCT_STOCK_PRODUCT;
