-- // DDL_Add_Stock_Flow
-- Migration SQL that makes the change goes here.

CREATE TABLE STOCK_FLOW(
  ID INTEGER AUTO_INCREMENT,
  QUANTITY INTEGER NOT NULL,
  PRICE_PER_UNIT DOUBLE NOT NULL,
  USER_ID INTEGER NOT NULL,
  TYPE VARCHAR(10) NOT NULL,
  INCLUDED BOOLEAN NOT NULL,
  TIME_ON_ENTRY TIMESTAMP NOT NULL,
  STOCK_PRODUCT_ID INTEGER NOT NULL,
  PRIMARY KEY PK_STOCK_FLOW(ID),
  FOREIGN KEY FK_STOCK_FLOW_ST_PROD(STOCK_PRODUCT_ID) REFERENCES STOCKPRODUCT(ID)
);

-- //@UNDO
-- SQL to undo the change goes here.

DROP TABLE STOCK_FLOW;
