-- // DDL_Add_Product_Preparation
-- Migration SQL that makes the change goes here.

CREATE TABLE PREPARATION(
  ID INTEGER AUTO_INCREMENT,
  QUEUE_NAME VARCHAR(30) NOT NULL,
  TIMER INTEGER NOT NULL,
  INSTRUCTIONS VARCHAR(250),
  PRODUCT_ID INTEGER NOT NULL,
  PRIMARY KEY PK_PREPARATION(ID),
  FOREIGN KEY FK_PREPARATION_PRODUCT(PRODUCT_ID) REFERENCES PRODUCT(ID)
);

-- //@UNDO
-- SQL to undo the change goes here.

DROP TABLE PREPARATION;
