-- // DDL_Add_ProductType
-- Migration SQL that makes the change goes here.

CREATE TABLE STOCKPRODUCT(
  ID INTEGER AUTO_INCREMENT,
  NAME VARCHAR(30) NOT NULL,
  STOCKLEVEL INTEGER NOT NULL DEFAULT 0,
  MAX_CONSUMPTIONS INTEGER NOT NULL DEFAULT 1,
  REMAINING_CONSUMPTIONS INTEGER NOT NULL DEFAULT 0,
  CLEARANCE VARCHAR(15) NOT NULL,
  PRODUCT_TYPE VARCHAR(15) NOT NULL,
  PRIMARY KEY (ID)
);

-- //@UNDO
-- SQL to undo the change goes here.

DROP TABLE STOCKPRODUCT;