-- // DDL_Add_Stock_Correction
-- Migration SQL that makes the change goes here.

CREATE TABLE STOCK_CORRECTION(
  ID INTEGER AUTO_INCREMENT,
  QUANTITY INTEGER NOT NULL,
  MESSAGE VARCHAR(100) NOT NULL,
  USER_ID INTEGER NOT NULL,
  STOCK_PRODUCT_ID INTEGER NOT NULL,
  CORRECTION_TIME DATETIME NOT NULL,
  PRIMARY KEY PK_STOCK_CORR(ID),
  FOREIGN KEY FK_STOCK_PROD_STOCK_CORR(STOCK_PRODUCT_ID) REFERENCES PRODUCT(ID)
);

-- //@UNDO
-- SQL to undo the change goes here.

DROP TABLE STOCK_CORRECTION;
