-- // DDL_Preparation_Task
-- Migration SQL that makes the change goes here.

CREATE TABLE PREPARATION_TASK(
  ID INTEGER AUTO_INCREMENT,
  QUEUE_TIME TIMESTAMP NOT NULL,
  START_TIME TIMESTAMP,
  STATUS VARCHAR(30) NOT NULL ,
  ORDER_LINE_ID INTEGER NOT NULL ,
  USER_ID INTEGER ,
  PRIMARY KEY PK_PREP_TASK(ID),
  FOREIGN KEY FK_TASK_ORDER_LIN(ORDER_LINE_ID) REFERENCES PRODUCT_ORDER_LINE(ID)
);

-- //@UNDO
-- SQL to undo the change goes here.

DROP TABLE PREPARATION_TASK;
