-- // DDL_Add_Order_Line
-- Migration SQL that makes the change goes here.

CREATE TABLE PRODUCT_ORDER_LINE(
  ID INTEGER AUTO_INCREMENT,
  PRODUCT_ID INTEGER NOT NULL,
  QUANTITY INTEGER NOT NULL,
  PRIMARY KEY PK_PRODUCT_ORDER_LINE(ID),
  FOREIGN KEY FK_ORDER_LINE_PRODUCT(PRODUCT_ID) REFERENCES PRODUCT(ID)
);

-- //@UNDO
-- SQL to undo the change goes here.

DROP TABLE PRODUCT_ORDER_LINE;
