CREATE TABLE product_supplement (
  product_id       BIGINT NOT NULL,
  stock_product_id BIGINT NOT NULL,
  CONSTRAINT PK_PRODUCT_SUPPLEMENT PRIMARY KEY (product_id, stock_product_id),
  CONSTRAINT FK_SUPPLEMENT_STOCK_PRODUCT FOREIGN KEY (STOCK_PRODUCT_ID) REFERENCES STOCKPRODUCT (ID),
  CONSTRAINT FK_SUPPLEMENT_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
)