CREATE TABLE PRODUCT_STOCK_PRODUCT(
  STOCK_PRODUCT_ID BIGINT NOT NULL,
  PRODUCT_ID BIGINT NOT NULL,
  QUANTITY INTEGER NOT NULL DEFAULT 1,
  CLEARANCE VARCHAR(15) NOT NULL,
  CONSTRAINT PK_PRODUCT_STOCK_PRODUCT PRIMARY KEY (STOCK_PRODUCT_ID, PRODUCT_ID),
  CONSTRAINT FK_RECEIPT_STOCK_PRODUCT FOREIGN KEY (STOCK_PRODUCT_ID) REFERENCES STOCKPRODUCT(ID),
  CONSTRAINT FK_RECEIPT_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);