CREATE TABLE STOCKPRODUCT(
  ID BIGSERIAL,
  NAME VARCHAR(30) NOT NULL,
  STOCKLEVEL INTEGER NOT NULL DEFAULT 0,
  MAX_CONSUMPTIONS INTEGER NOT NULL DEFAULT 1,
  REMAINING_CONSUMPTIONS INTEGER NOT NULL DEFAULT 0,
  CLEARANCE VARCHAR(15) NOT NULL,
  PRODUCT_TYPE VARCHAR(15) NOT NULL,
  CONSTRAINT PK_STOCKPRODUCT PRIMARY KEY (ID)
);