CREATE TABLE STOCK_FLOW(
  ID BIGSERIAL,
  USER_ID BIGINT NOT NULL,
  TYPE VARCHAR(10) NOT NULL,
  INCLUDED BOOLEAN NOT NULL,
  TIME_ON_ENTRY TIMESTAMP NOT NULL,
  CONSTRAINT PK_STOCK_FLOW PRIMARY KEY (ID)
);