CREATE TABLE PRODUCT_RECEIPT_LINE(
  ID BIGSERIAL,
  STOCK_PRODUCT_ID BIGINT NOT NULL,
  PRODUCT_ID BIGINT NOT NULL,
  QUANTITY INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT PK_PRODUCT_STOCK_PRODUCT PRIMARY KEY (ID),
  CONSTRAINT FK_RECEIPT_STOCK_PRODUCT FOREIGN KEY (STOCK_PRODUCT_ID) REFERENCES STOCKPRODUCT(ID),
  CONSTRAINT FK_RECEIPT_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);