CREATE TABLE PRODUCT_ORDER(
  ID BIGSERIAL,
  TIMESTAMP TIMESTAMP NOT NULL,
  STATUS VARCHAR(15) NOT NULL,
  USER_ID BIGINT NOT NULL,
  PLACED_BY_USER_ID BIGINT NOT NULL,
  CONSTRAINT PK_PRODUCT_ORDER PRIMARY KEY (ID)
);