CREATE TABLE PRODUCT(
  ID BIGSERIAL,
  NAME VARCHAR(30) NOT NULL,
  PRODUCT_TYPE VARCHAR(15) NOT NULL,
  PRICE DECIMAL NOT NULL,
  AVAILABLE BIT(1) NOT NULL,
  CONSTRAINT PK_PRODUCT PRIMARY KEY (ID)
);