CREATE TABLE STOCK_FLOW_DETAIL(
  ID BIGSERIAL,
  QUANTITY INTEGER NOT NULL,
  PRICE_PER_UNIT DECIMAL NOT NULL,
  STOCK_FLOW_ID BIGINT NOT NULL,
  STOCK_PRODUCT_ID BIGINT NOT NULL,
  CONSTRAINT PK_STOCK_FLOW_DETAIL PRIMARY KEY (ID),
  CONSTRAINT FK_STOCK_FLOW_DETAIL_STOCK_FLOW FOREIGN KEY (STOCK_FLOW_ID) REFERENCES stock_flow (ID),
  CONSTRAINT FK_STOCK_FLOW_DETAIL_ST_PROD FOREIGN KEY (STOCK_PRODUCT_ID) REFERENCES stockproduct (ID)
);